#!/usr/bin/env bash
#
# Slurm arguments
#
#SBATCH --job-name=deepchess        # Name of the job 
#SBATCH --export=ALL                # Export all environment variables
#SBATCH --output=logs/test.log      # Log-file (important!)
#SBATCH --cpus-per-task=2           # Number of CPU cores to allocate
#SBATCH --mem-per-cpu=4G            # Memory to allocate per allocated CPU core
#SBATCH --gres=gpu:1                # Number of GPU's
#SBATCH --time=1:00:00              # Max execution time
#

cd $SLURM_SUBMIT_DIR
# Activate your Anaconda environment
source $(conda info --base)/etc/profile.d/conda.sh
conda activate /home/adelandsheere/anaconda3/envs/deepchess

# Run your Python script
python src/viz_attention.py